spring:
  application:
    name: test
  cloud:
    stream:
      bindings:
        invoiceInput:
          destination: invoice-topic
          group: invoice-group
        orderInput:
          destination: order-topic
          group: order-group

        invoiceOutput:
          destination: invoice-topic
        orderOutput:
          destination: order-topic
      default-binder: rabbit

spring.cloud.stream.kafka.binder:
  brokers: kafka
  defaultBrokerPort: 9092

spring.rabbitmq:
  host: rabbitmq
  port: 5672
  username: guest
  password: guest

# Profile for kafka (activated when using the 'kafka' profile)
---
spring:
  config:
    activate:
      on-profile: kafka
  cloud:
    stream:
      default-binder: kafka
      kafka:
        binder:
          brokers: kafka:9092
# Profile for RabbitMQ (activated when using the 'rabbitmq' profile)
---
spring:
  config:
    activate:
      on-profile: rabbitmq
  cloud:
    stream:
      default-binder: rabbit
  rabbitmq:
    host: rabbitmq

